### PR TITLE
GSoC 2021 announcement

### PR DESCRIPTION
**Pull request by Jbalkind**
Based heavily on previous years' announcements :)

### CODE REVIEW

**Comment by mithro** [comment]
It would be good if you crosslinked to the SymbiFlow + Apertus GSoC pages too.

**Comment by Jbalkind** [comment]
Could you share a link to those?

**Comment by mithro** [comment]
* [Apertus](https://summerofcode.withgoogle.com/organizations/5025744687726592/)
 * [SymbiFlow](https://summerofcode.withgoogle.com/organizations/5137353372336128/)
 * [BeagleBoard.org Foundation](https://summerofcode.withgoogle.com/organizations/6398417846140928/)

**Comment by Jbalkind** [comment]
Thanks - updated!

**Pull request merged**
