### PR TITLE
OSFPGA wasn't accepted into GSoC, so pulling in 2 of my favorites fro…

### PR DESCRIPTION
**Pull request by stevehoover**
…m the OSFPGA list.

### CODE REVIEW

**Comment by Jbalkind** [comment]
Is the mentoring with Efabless confirmed? Could we indicate exactly who the other mentors might be?

**Comment by stevehoover** [comment]
Yes

- mohamed
+1.650.889.8145 
 γνῶθ σεαυτόν

**Comment by Jbalkind** [comment]
Ok can you update the entry and resolve conflicts with the branch?

**Comment by stevehoover** [comment]
Done

**Comment by Jbalkind** [comment]
Thanks!

**Pull request merged**
